### PR TITLE
feat: lanczos downscaling

### PR DESCRIPTION
**Pull request by r3tr0ananas**
391517358-61624ee3-1781-4ef7-904c-0e6e7fa35f1a

Image used: https://cdn.ananas.moe/lanczos_test.jpg

### CODE REVIEW

**Comment by THEGOLDENPRO** [comment]
I will have to hardcore test this with my test images.

Also how does Lanczos filtering work again? I need this code a little more commented.

**Comment by r3tr0ananas** [comment]
idk how to explain lanczos, my brain is fried. https://en.wikipedia.org/wiki/Lanczos_resampling

**Comment by r3tr0ananas** [comment]
Hope that comment explains it

**Comment by THEGOLDENPRO** [comment]
Can we name some variables better, like what is `a` meant to be?

Also is `lanczos_window` basically `square_block_size`? _(I'm just trying to understand exactly how this works, I'll read more into that wiki later™)_

https://github.com/cloudy-org/roseate/blob/main/src/image/fast_downsample.rs#L30-L33

**Comment by THEGOLDENPRO** [comment]
Alright starting to understand this...

**Comment by THEGOLDENPRO** [comment]
I don't know if it's gotten slower or what but image-rs down-sampling is faster with every other image except purposely large images like `uwu_bomb.png`. Lanczos is naturally more expensive so I expect it to be slower than the previews algorithm but now I got to compare the two versions and see if I can somehow improve it.

**Comment by THEGOLDENPRO** [comment]
Imagine this on an AMD Threadripper 💀 you'll be able to downsample 8k images A LOT faster.

BTW I do have a potential solution I could try to speed this up, i just don't know I'll work until I actually implement it and test it A LOT as we might be talking about very small milliseconds of improvement.

**Comment by THEGOLDENPRO** [comment]
performance issues fixed! It's a lot faster than the image-rs backend now with all images I've tested so far.

image

**Comment by THEGOLDENPRO** [comment]
During my tests I found the roseate backend having issues with some images

Screenshot_20241208_214114

going back versions this issue has existed since I wrote the first iteration though so I can still close this pr, thanks!

**Pull request merged**
