### PR TITLE
feat: drag and drop

### PR DESCRIPTION
**Pull request by r3tr0ananas**
drag and drop yippie!!!

> [!NOTE]
> This doesn't work on wayland :(
> See https://github.com/rust-windowing/winit/issues/1881

image

### CODE REVIEW

**Comment by THEGOLDENPRO** [comment]
I think I'll just wait for wayland support

umaru-sleeping

**Comment by r3tr0ananas** [comment]
The issue opened 4 years ago, I don't think they'll add it in the next years. It works fine on every other device except Wayland.

**Comment by THEGOLDENPRO** [comment]
The pr is all good, now I just need to work on the dropping image attachment thingy I was talking about on Discord.

**Comment by r3tr0ananas** [comment]
image

idk how to get the text closer to the rose without breaking centering stuff.

**Comment by THEGOLDENPRO** [comment]
> idk how to get the text closer to the rose without breaking centering stuff.

I can try and fix that don't worry about it

**Comment by THEGOLDENPRO** [comment]
Screenshot_20241115_191146

**Comment by THEGOLDENPRO** [comment]
I'm kinda confused, why is `self.dropped_files` even needed, can't we just use `&i.raw.dropped_files`? Is there a reason why we need to clone from `&i.raw.dropped_files` to `self.dropped_files`.

**Comment by r3tr0ananas** [comment]
🔥

**Comment by r3tr0ananas** [comment]
> I'm kinda confused, why is `self.dropped_files` even needed, can't we just use `&i.raw.dropped_files`? Is there a reason why we need to clone from `&i.raw.dropped_files` to `self.dropped_files`.

not really, i just copied that from the example.

**Comment by THEGOLDENPRO** [comment]
just saw the egui example, interesting...

**Pull request merged**
