### PR TITLE
feat: Drag and Drop dialog

### PR DESCRIPTION
**Pull request by r3tr0ananas**
dark mode:
image

light mode: 
image

### CODE REVIEW

**Comment by r3tr0ananas** [comment]
i couldn't use the public folder probably because it's not in the same directory.

Used a different image because the other one is too pixelated.

**Comment by THEGOLDENPRO** [comment]
> I couldn't use the public folder probably because it's not in the same directory.

Couldn't you like `../public`. Does that work?

**Comment by r3tr0ananas** [comment]
> > I couldn't use the public folder probably because it's not in the same directory.
> 
> Couldn't you like `../public`. Does that work?

that didn't work...

**Comment by r3tr0ananas** [comment]
image

this worked 

image

**Comment by THEGOLDENPRO** [comment]
There're also some design adjustments I wanna make but I'll either do them later today or tomorrow.

**Comment by r3tr0ananas** [comment]
What should be changed?

I'll try and do that.

**Comment by THEGOLDENPRO** [comment]
dw I'll work on it, I'm just gonna merge this into a branch on the repo first.

**Comment by THEGOLDENPRO** [comment]
discussions can be continued in #10

**Pull request merged**
