### PR TITLE
Feat/drag and drop

### PR DESCRIPTION
**Pull request by THEGOLDENPRO**
continuation of #9

### CODE REVIEW

**Comment by THEGOLDENPRO** [comment]
did some improvements in the design

image

**Comment by THEGOLDENPRO** [comment]
In light mode white text wouldn't do so I placed a border behind it but as you can see it's taking the whole space.

image

It should fit with the length of the text. I'm too tired rn to figure out why and tomorrow I got to wake up early to go somewhere so...

**Comment by r3tr0ananas** [comment]
image

You mean something like this?

**Comment by THEGOLDENPRO** [comment]
> image
> 
> You mean something like this?

Not quite, the rounded corners yes, keep that but I meant the width of the div being the same as the text.

I wasn't able to find out why I couldn't do that in time yesterday.

**Comment by r3tr0ananas** [comment]
image

**Comment by THEGOLDENPRO** [comment]
Nice, now add `px-2` to the text and it should be good.

**Comment by THEGOLDENPRO** [comment]
all good!

**Pull request merged**
